### PR TITLE
Common module

### PR DESCRIPTION
**Pull request by carterhudson**
It was really tedious duplicating updates across resource files for the Kotlin & Java projects, so I extracted the common resources & dependencies to a common module. If we don't want to do this, we can kill this PR.

(won't build on CI until https://github.com/GetStream/stream-chat-android/pull/1229 is merged and stream dependency is updated)

### CODE REVIEW

**Comment by adasiewiczr** [comment]
I'm not sure if we should do that - copying resources is annoying but I think that most of the users expect that tutorial is as easy and straightforward as possible (so they can open a project and copy everything from one module). We also had a common dependencies configuration for both modules but we get rid of it to simplify things.

**Comment by carterhudson** [comment]
> I'm not sure if we should do that - copying resources is annoying but I think that most of the users expect that tutorial is as easy and straightforward as possible (so they can open a project and copy everything from one module). We also had a common dependencies configuration for both modules but we get rid of it to simplify things.

That's fair, and I also had that concern, but do we ever link to the tutorial github anywhere? I'm under the impression that this is a repository for us, and we use its contents to curate the tutorial, since I can't find a link to this repo anywhere on the tutorial page.

**Comment by zsmb13** [comment]
If we don't link it anywhere, it's time to add a link to the start and end of the tutorial so that people can check out a working project if they want to 😉

**Comment by adasiewiczr** [comment]
I thought it's linked 🙈  We should definitely add it

**Pull request closed without merging**
